---

- name: 'start mysql'
  become: yes
  service:
    name: '{{ mysql_service_name }}'
    state: 'started'

- name: 'stop mysql'
  become: yes
  service:
    name: '{{ mysql_service_name }}'
    state: 'stopped'

- name: 'restart mysql'
  become: yes
  service:
    name: '{{ mysql_service_name }}'
    state: 'restarted'